### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by wwgordon** [kaustubhad/fastman#1]
I'm unable to install the package using devtools:

```
> devtools::install_github("kaustubhad/fastman")
Downloading GitHub repo kaustubhad/fastman@HEAD
Error: Failed to install 'fastman' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
```

Is there a different, preferred method of installation?

Thanks!

**Comment by soumyasubhraparia** [comment]
Apologies for late response. This has been fixed now. You can use the following code

`devtools::install_github('kaustubhad/fastman', build_vignettes = TRUE)`

Please let me know in case you face any other problems in downloading/using the package.

**Comment by wwgordon** [comment]
Fantastic, I've tested the fix and it works beautifully on my end.

Cheers,
William
