### ISSUE TITLE
How to set col with just one color?

### ISSUE THREAD

**Issue by michaelofrancis** [kaustubhad/fastman#11]
Hi, I want to color all points above the threshold as one color. I thought I could set a hex code for col, i.e. col="#DC7633", but that doesn't work. Any help would be appreciated. Thanks!

**Comment by kaustubhad** [comment]
Hi,
If it is a single string, then it tries to match to one of the internal palette names, so you need a little hack: repeat the same color string twice, e.g. specify col=c("#DC7633","#DC7633").
Please let me know if this doesn't work for you.

**Comment by michaelofrancis** [comment]
That gave me this error:

Error in if (col == "greys") { : the condition has length > 1

**Comment by soumyasubhraparia** [comment]
Hi @michaelofrancis ,

I have fixed the problem now and have updated the package. You can try using the following code.

`fastman(m,annotatePval = 2,colAbovePval = TRUE,col = c("#DC7633","#DC7633"))`

You can find the output of this code snippet below.

![check](https://user-images.githubusercontent.com/76999235/193039982-21747e03-1acd-4f61-a39a-bb1b75f745ce.png)
Please let me know if this works for you.
