### ISSUE TITLE
maxP not working correctly?

### ISSUE THREAD

**Issue by guidebortoli** [kaustubhad/fastman#15]
Hi,

I have a plot where the signals I got go to 10-3 only...
So the plot automatically sets the ylim to 4...
I am trying to set it to 10 because even though it is far from my signals I would like to draw a significant line at around 5...

When I try to set the maxP = 10 nothing happens.
When I try to set the maxP = 2 for example, it works...

Is there a way to set the ylim when it is above the signals you got?

Best,
Guilherme

**Comment by soumyasubhraparia** [comment]
Hello. Thank you for using our package.

The `maxP` argument helps you in truncating the Y axis range of your plot. However, if you wish to extend the Y axis range of your plot, you need to use the `ylim` argument directly. The following piece of code should work.

`
fastman(m, ylim=c(0,10)) 
`

Let me know if this solves your problem.
