### ISSUE TITLE
Overlapping labels

### ISSUE THREAD

**Issue by UrsaGitHub** [kaustubhad/fastman#16]
Hello,

I would like to add labels to the significant SNPs, but the labels are overlapping. Is there any option to remove the overlapping labels? Any help would be appreciated. Thanks!

**Comment by kaustubhad** [comment]
Hi,
Sorry for the late response.  If you are showing multiple SNP labels in a cluster, such as the example we show in the readme by setting annotateTop=FALSE, then yes, there is no way to avoid overlaps. As far as I understand, this is only achievable by more complex packages such as ggrepel, and we are in the process of implementing a ggplot version of the code. 
But annotateTop is true by default, so formally you would only see a single SNP label per peak, so the issue of overlap wouldn't arise.
Thanks,
Kaustubh.
