### ISSUE TITLE
Altering annotation text

### ISSUE THREAD

**Issue by hollypoore** [kaustubhad/fastman#21]
Hi - I'm wondering if there's a way to change the size of the text when we use any of the annotate functions. I have labeled the genes mapped to certain loci, but the text is very small and gray and therefore hard to read. I am also not able to modify the text size using theme() when I make the plot as a ggplot object with fastman_gg. Thanks!

**Comment by soumyasubhraparia** [comment]
Hi.

Thank you for using fastman. You can use the `cex.text` parameter in both `fastman()` and `fastman_gg()` to modify the text size. Please check the readme for the default values used so that you can increase those values.
