### ISSUE TITLE
Error in round(ms$p, digits = digs) when running fastqq

### ISSUE THREAD

**Issue by agung-m** [kaustubhad/fastman#4]
Hi,
Fastqq seems not working.

> data = fread('data.qassoc')
> fastqq(p1 = data[['P']])
Error in round(ms$p, digits = digs) : 
  non-numeric argument to mathematical function

* I use R v4.2

**Comment by kaustubhad** [comment]
Hi, have you checked that the P column you are providing is numeric? You can check by trying
is.numeric(data[['P']])
Maybe you have numbers in that column but coded as strings? If the problem persists, please let us know.

**Comment by agung-m** [comment]
Yes, they are numeric.
I also tried with random generated values:

> p = runif(1000, min=0, max=1)
> fastqq(p1=p)
Error in round(ms$p, digits = digs) : 
  non-numeric argument to mathematical function


I think the problem is on line 95 of R/fastqq.R:
```
m=as.data.frame(cbind(p1,p2));
if (speedup) {
       # Line 95
       digs=3; ms=m; ms$p1=round(ms$p,digits=digs); ms$p2=round(ms$p2,digits=digs); f=duplicated(ms); ms=ms[!f,];
    }
```

**Comment by soumyasubhraparia** [comment]
Hi, thanks for pointing this out. We have looked into the code and identified the bug. The bug has been fixed and an updated version has been uploaded.

Your code should work now if you uninstall and re-install the package. Please let me know if this helps.

**Comment by agung-m** [comment]
Thanks, it is solved now.
There is an issue that reference line exceeds the plot range. I will create another issue for this.
