### ISSUE TITLE
Fastqq plots reference line outside the axis range

### ISSUE THREAD

**Issue by agung-m** [kaustubhad/fastman#5]
Hi,
I tried this:

```
> p = runif(100, min=0, max=1)
> fastqq(p1=p)
```
![fastqq_plot_outside_range](https://user-images.githubusercontent.com/48218002/176880038-d5d5df09-d3c4-4cad-9e51-3b9613e1e9bb.jpg)

**Comment by soumyasubhraparia** [comment]
Sorry for the late reply.

This should not be a problem for the more recent versions of `fastqq()`.
