### ISSUE TITLE
Undefiend exports error when trying to install fastman?

### ISSUE THREAD

**Issue by Johnny555l** [kaustubhad/fastman#7]
I am running the following code:
install.packages("remotes", repos = "http://cran.us.r-project.org", lib="/z/Comp/lu_group/Members/jwlorge/ATN/R")
remotes::install_github("danioreo/fastman",lib = "/z/Comp/lu_group/Members/jwlorge/ATN/R")
 Which gives me the following error:
Error: package or namespace load failed for ‘fastman’ in namespaceExport(ns, exports):
 undefined exports: fastman
Error: loading failed
Execution halted
ERROR: loading failed
 removing ‘/z/Comp/lu_group/Members/jwlorge/ATN/R/fastman’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpZYg1zb/file12c3d26c90b542/fastman_0.1.0.tar.gz’ had non-zero exit status

When searching online, I found someone who had the same issue for a different function and it looked like it had to be fixed by github itself? I would appreciate any help or advice!

**Comment by kaustubhad** [comment]
Hi, sorry for the late reply. I think you are trying to install a different package by a different author which is also named fastman. If you try to install the kaustubhad/fastman package from github, and you have no other packages named fastman already installed, it should not give you a problem.

**Comment by gmissir** [comment]
@kaustubhad Thanks for the prompt reply, literally having the same issue.

This is what I get when I try to install it > install.packages(kaustubhad/fastman)
Error in install.packages : object 'kaustubhad' not found

Any ideas?

**Comment by soumyasubhraparia** [comment]
Hi @Johnny555l and @gmissir . You can try using the following code.

`devtools::install_github('kaustubhad/fastman',build_vignettes = TRUE)`

Please let me know if this works.
