### ISSUE TITLE
Title on plot

### ISSUE THREAD

**Issue by michaelofrancis** [kaustubhad/fastman#9]
Hi, is there an option to put a title on the plot?  I need this because I have supplementary figures where there will be many plots and they need to be labeled.

Thanks!

**Comment by michaelofrancis** [comment]
Nevermind, I see that "main = " can be used to set that. This does not appear in the readme.

**Comment by kaustubhad** [comment]
Indeed, thanks for pointing it out. We will clarify it in the readme.
